
perfumes = [
    ("Dior Sauvage","Amaderado","Alta","Formal","Noche",120),
    ("Bleu de Chanel","Cítrico","Media","Elegante","Trabajo",135),
    ("Versace Eros","Dulce","Alta","Juvenil","Fiesta",95),
    ("Acqua di Gio Profumo","Acuático","Media","Casual","Diario",110),
    ("Paco Rabanne 1 Million","Especiado","Alta","Juvenil","Fiesta",100),
    ("Hugo Boss Bottled","Frutal","Media","Elegante","Trabajo",85),
    ("Armani Code","Oriental","Alta","Formal","Noche",125),
    ("YSL Y EDP","Aromático","Media","Moderno","Diario",115),
    ("Dolce & Gabbana The One","Amaderado","Alta","Elegante","Cita",130),
    ("Jean Paul Gaultier Le Male","Dulce","Media","Clásico","Fiesta",105),

    ("Tom Ford Noir","Oriental","Alta","Formal","Evento",150),
    ("Montblanc Explorer","Amaderado","Media","Casual","Aventura",90),
    ("Givenchy Gentleman","Amaderado","Alta","Formal","Trabajo",140),
    ("Creed Aventus","Frutal","Alta","Lujo","Evento",300),
    ("Bentley Intense","Especiado","Alta","Formal","Noche",95),
    ("Lattafa Asad","Especiado","Alta","Moderno","Fiesta",60),
    ("Rasasi Hawas","Aromático","Media","Juvenil","Verano",75),
    ("Afnan 9PM","Dulce","Alta","Juvenil","Noche",50),
    ("Viktor & Rolf Spicebomb","Especiado","Alta","Moderno","Invierno",120),
    ("Burberry Hero","Amaderado","Media","Elegante","Trabajo",110),

    ("Carolina Herrera Bad Boy","Oriental","Alta","Moderno","Noche",115),
    ("Issey Miyake L’Eau d’Issey","Cítrico","Media","Clásico","Verano",95),
    ("Club de Nuit Intense Man","Amaderado","Alta","Moderno","Diario",70),
    ("Mancera Cedrat Boise","Cítrico","Alta","Lujo","Evento",140),
    ("Invictus Victory","Dulce","Alta","Juvenil","Fiesta",105),
    ("Dolce & Gabbana Light Blue Homme","Cítrico","Media","Casual","Verano",85),
    ("CK One","Cítrico","Baja","Casual","Diario",55),
    ("Eros Flame","Especiado","Alta","Juvenil","Fiesta",110),
    ("Fahrenheit","Oriental","Alta","Clásico","Noche",100),
    ("212 VIP Men","Oriental","Alta","Moderno","Fiesta",120),

    ("Bvlgari Man in Black","Oriental","Alta","Formal","Noche",135),
    ("Prada Luna Rossa Carbon","Amaderado","Media","Moderno","Diario",115),
    ("Valentino Uomo","Amaderado","Alta","Elegante","Cita",145),
    ("Boss The Scent","Oriental","Media","Elegante","Cita",110),
    ("Azzaro Wanted","Aromático","Media","Juvenil","Fiesta",95),
    ("Nautica Voyage","Acuático","Media","Casual","Diario",40),
    ("Abercrombie & Fitch Fierce","Amaderado","Media","Juvenil","Diario",90),
    ("Lacoste Blanc","Cítrico","Media","Casual","Diario",95),
    ("Diesel Only The Brave","Oriental","Alta","Juvenil","Fiesta",85),
    ("John Varvatos Artisan","Cítrico","Media","Casual","Diario",75),

    ("Maison Francis Kurkdjian Baccarat Rouge 540","Oriental","Alta","Lujo","Evento",320),
    ("Parfums de Marly Layton","Amaderado","Alta","Lujo","Evento",280),
    ("Xerjoff Naxos","Oriental","Alta","Lujo","Evento",350),
    ("Amouage Interlude Man","Amaderado","Alta","Lujo","Evento",360),
    ("Emporio Armani Stronger With You","Dulce","Alta","Moderno","Cita",125),
    ("Paco Rabanne Phantom","Aromático","Media","Moderno","Fiesta",115),
    ("Yves Saint Laurent Y Le Parfum","Aromático","Alta","Moderno","Noche",140),
    ("Jean Paul Gaultier Ultra Male","Dulce","Alta","Juvenil","Fiesta",120),
    ("Salvatore Ferragamo Uomo","Oriental","Alta","Elegante","Cita",100),
    ("Ralph Lauren Polo Blue","Acuático","Media","Clásico","Trabajo",95),

    ("Ralph Lauren Polo Red","Especiado","Alta","Moderno","Fiesta",105),
    ("Dunhill Icon","Amaderado","Media","Elegante","Trabajo",150),
    ("Kenzo Homme","Acuático","Media","Casual","Verano",90),
    ("Calvin Klein Eternity","Aromático","Media","Clásico","Trabajo",85),
    ("Thierry Mugler A*Men","Oriental","Alta","Clásico","Noche",95),
    ("Hermès Terre d’Hermès","Amaderado","Media","Elegante","Trabajo",130),
    ("Initio Oud for Greatness","Oriental","Alta","Lujo","Evento",380),
    ("Byredo Gypsy Water","Amaderado","Media","Lujo","Diario",250)
]